### ISSUE TITLE
papercuts

### ISSUE THREAD

**Issue by dvc94ch** [cloudpeers/ffi-gen#28]
- [x] identifiers should respect language conventions (#5)
- [x] support for doc comments in rsh (#6)
- [x] handle non ascii strings (currently we use the byte length when encoding) (#24)
- [x] support returning results from futures/streams
- [x] support nested options
- [x] more interesting slices/vecs
- [x] tuples
- [x] get streams working
